<?php
module_load_include('inc', 'pathauto', 'pathauto');

function pathauto_batch_menu() {
  $items = array();

  $items['admin/build/path/pathauto_batch'] = array(
    'title' => 'Batch Generate Path Alias',
    'description' => 'Bulk generate path aliases using the Batch API.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('pathauto_batch_form'),
    'access callback' => TRUE,
    'type' => MENU_LOCAL_TASK,
    'weight' => 10,
  );

  return $items;
}

function pathauto_batch_form(&$form_state) {
  $form = array();

  $form['node_types'] = array(
    '#type' => 'checkboxes',
    '#title' => 'Node types',
    '#options' => array_map('check_plain', node_get_types('names')),
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Batch generate aliases',
  );

  return $form;
}

function pathauto_batch_form_submit($form, &$form_state) {
  $batch = array(
    'title' => t('Generating Aliases'),
    'finished' => 'pathauto_batch_finished',
    'progress_message' => t('Processed @current out of @total.'),
    'error_message' => t('Pathauto Batch has encountered an error.'),
  );

  $types = array_filter($form_state['values']['node_types']);

  foreach ($types AS $type) {
    $batch['operations'][] = array('pathauto_batch_node', array($type));
  }

  batch_set($batch);
}

function pathauto_batch_node($type, &$context) {
  if (empty($context['sandbox'])) {
    $context['sandbox']['progress'] = 0;
    $context['sandbox']['current_node'] = 0;
    $context['sandbox']['max'] = db_result(db_query("SELECT COUNT(DISTINCT nid) FROM {node} WHERE type = '%s'", $type));
  }

  if ($context['sandbox']['max'] == 0) {
    $context['message'] = t('No nodes found belonging to %type.', array('%type' => $type));
    $context['finished'] = 1;
  }
  else {
    $placeholders = array();
    $limit = variable_get('pathauto_batch_limit', 5);
    $result = db_query_range("SELECT nid FROM {node} WHERE nid > %d AND type = '%s' ORDER BY nid ASC", $context['sandbox']['current_node'], $type, 0, $limit);

    while ($row = db_fetch_array($result)) {
      $node = node_load($row['nid'], NULL, TRUE);
      $placeholders = pathauto_get_placeholders('node', $node);
      $src = "node/$node->nid";

      if (pathauto_create_alias('node', 'update', $placeholders, $src, $node->nid, $node->type, $node->language) != NULL) {
        $context['results'][] = $node->title .' : '. drupal_get_path_alias('node/' . $node->nid);
      }

      $context['sandbox']['progress']++;
      $context['sandbox']['current_node'] = $node->nid;
    }

    if ($context['sandbox']['progress'] != $context['sandbox']['max']) {
      $context['finished'] = $context['sandbox']['progress'] / $context['sandbox']['max'];
    }
  }
}

function pathauto_batch_finished($success, $results, $operations) {
  if ($success) {
    $message = format_plural(count($results), 'One alias generated.', '@count aliases generated.');
  }
  else {
    $message = t('Finished with an error.');
  }
  drupal_set_message($message);
}
